# Generated by Django 5.0.7 on 2024-07-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_added_query_histore_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='last_query',
            field=models.CharField(max_length=100, null=True, verbose_name='Введите название города'),
        ),
    ]
