# Generated by Django 5.0.7 on 2024-07-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_added_statistic_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
    ]
