# Generated by Django 5.0.7 on 2024-07-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_rename_device_id_field_in_query_history_model_to_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
